### ISSUE TITLE
[Bug]: Windows 10 - Server Crash in DM when player joining the game

### ISSUE THREAD

**Issue by TheEnergy** [kus/cs2-modded-server#101]
### Server is up to date

- [X] My server is up-to-date and I'm using the latest version of this mod from this github.

### I've followed the instructions

- [X] I've followed the instructions

### Game Server Login Token

- [X] I'm using a valid Game Server Login Token or running on LAN

### Operating System

Windows 10

### Which mod are you playing

Deathmatch

### Are you trying to host online or on LAN?

Online off a machine on my local network

### Metamod:Source Version

2.2.2.-dev+1291

### Metamod:Source Plugins loaded

CounterStrikeSharp

### CounterStrikeSharp Version

V233

### CounterStrikeSharp Plugins loaded

1.1.1 Deathmatch core

### What is the bug

Server starts and running DM mod. Crashed when player join and select a team

### Steps to reproduce

Starter server with DM mod in windows 10
Join server and select team

**Comment by mavproductions** [comment]
@TheEnergy see [PR#123](https://github.com/kus/cs2-modded-server/pull/123) for a fix

**Comment by kus** [comment]
Deathmatch has now been updated to the latest version.
