### ISSUE TITLE
[Bug]: Docker not working

### ISSUE THREAD

**Issue by tklostermannNSD** [kus/cs2-modded-server#102]
### Server is up to date

- [X] My server is up-to-date and I'm using the latest version of this mod from this github.

### I've followed the instructions

- [X] I've followed the instructions

### Game Server Login Token

- [X] I'm using a valid Game Server Login Token or running on LAN

### Operating System

Linux Ubuntu 22.04

### Which mod are you playing

Competitive

### Are you trying to host online or on LAN?

Online off a machine on my local network

### Metamod:Source Version

cant see

### Metamod:Source Plugins loaded

cant see

### CounterStrikeSharp Version

cant see

### CounterStrikeSharp Plugins loaded

cant see

### What is the bug

The docker server is not starting. See the server log section for more information. I guess the docker-install.sh copies the steam client in the wrong folder or got premission issues.
I am running this in docker on a Ubuntu 22.04 host

### Server log output

```shell
dlopen failed trying to load:
steamclient.so
with error:
steamclient.so: cannot open shared object file: No such file or directory
dlopen failed trying to load:
/home/steam/.steam/sdk64/steamclient.so
with error:
/home/steam/.steam/sdk64/steamclient.so: cannot open shared object file: No such file or directory
[S_API] SteamAPI_Init(): Failed to load module '/home/steam/.steam/sdk64/steamclient.so'
 0 Failed to initialize Steamworks SDK for gameserver.  Failed to load module '/home/steam/.steam/sdk64/steamclient.so'
...
SteamGameServer_Init()
Failed to initialize Steamworks SDK for gameserver.  Failed to load module '/home/steam/.steam/sdk64/steamclient.so'
/home/cs2-modded-server/install_docker.sh: line 207:   264 Segmentation fault      sudo -u $user /home/steam/cs2/game/bin/linuxsteamrt64/cs2 -dedicated -console -usercon -autoupdate -tickrate $TICKRATE $IP_ARGS -port $PORT +map de_dust2 -maxplayers $MAXPLAYERS -authkey $API_KEY +sv_setsteamaccount $STEAM_ACCOUNT +game_type 0 +game_mode 0 +mapgroup mg_active
```

**Comment by phyzical** [comment]
@tklostermannNSD give the readme update a try https://github.com/kus/cs2-modded-server/pull/174
