### ISSUE TITLE
[Bug]: KZ/Sharptimer binds doesnt work

### ISSUE THREAD

**Issue by Kjerne** [kus/cs2-modded-server#105]
### Server is up to date

- [X] My server is up-to-date and I'm using the latest version of this mod from this github.

### I've followed the instructions

- [X] I've followed the instructions

### Game Server Login Token

- [X] I'm using a valid Game Server Login Token or running on LAN

### Operating System

Linux Ubuntu 22.04

### Which mod are you playing

KZ

### Are you trying to host online or on LAN?

LAN off a machine on my local network

### Metamod:Source Version

2.0.0-dev+1291

### Metamod:Source Plugins loaded

CounterStrikeSharp (v233 @ 02d5191) by Roflmuffin

### CounterStrikeSharp Version

 Current API Version: v233 (1.0.233+02d5191)

### CounterStrikeSharp Plugins loaded

 [Client]   List of all plugins currently loaded by CounterStrikeSharp: 12 plugins loaded. [Client]   [#1:LOADED]: "CS2_ExecAfter" (1.0.0) by Kus (https://github.com/kus) [Client]     Executes a command after server event or a delay. exec_after for help [Client]   [#2:LOADED]: "Custom Votes" (1.0.1) by imi-tat0r [Client]     Allows you to create custom votes for your server. [Client]   [#3:LOADED]: "[Custom] Map Configurator" (V. 1.0.2 [Beta]) by Manifest @Road To Glory [Client]     Allow server owners to easily create unique configuration files on a per map basis. [Client]   [#4:LOADED]: "GameModeManager" (1.0.3) by Striker-Nick [Client]     A simple plugin/module that dynamically updates any maplist.txt file based on the current mapgroup. [Client]   [#5:LOADING]: "SimpleAdmin" (0.1.2) [Client]   [#6:LOADED]: "CS2Rcon" (1.2.0) by LordFetznschaedl [Client]     Allows for server commands to be executed from the client using !rcon [Client]   [#7:LOADED]: "RockTheVote" (1.8.5) by abnerfs [Client]     https://github.com/abnerfs/cs2-rockthevote [Client]   [#8:UNLOADED]: "Open Prefire Prac" (0.1.32) by Lengran [Client]     A plugin for practicing prefire in CS2. https://github.com/lengran/OpenPrefirePrac [Client]   [#9:UNLOADED]: "MatchZy" (0.7.9) by WD- (https://github.com/shobhit-pathak/) [Client]     A plugin for running and managing CS2 practice/pugs/scrims/matches! [Client]   [#10:UNLOADED]: "Executes Plugin" (1.0.2) by zwolof, B3none [Client]     Community executes for CS2. [Client]   [#11:LOADED]: "Remove Map Weapons" (1.0.1) by Kus (https://github.com/kus) [Client]     Remove the weapons from the map [Client]   [#12:LOADED]: "SharpTimer" (0.2.5 - 5/3/2024 8:18:07 AM) by dea https://github.com/deafps/ [Client]     A CS2 Timer Plugin

### What is the bug

I cant use any binds with kz, it works when i type normally !cp or !tp, but when i put it in a bind nothing happens even though my bind writes !cp and !tp in the chat

Ways i tried

bind "scancode6" "say !css_cp"
bind "scancode25" "say !css_tp"
bind "scancode6" "say !css_cp"
bind "scancode25" "say !css_tp"
bind "scancode6" "say /css_cp"
bind "scancode25" "say /css_tp"
bind "scancode6" "/css_cp"
bind "scancode25" "/css_tp"
bind "scancode6" "!css_cp"
bind "scancode25" "!css_tp"

**Comment by Mr-Robot-ops** [comment]
I think that's the least of the problems. 
The owner and the project have completely disappeared
[https://github.com/deafps/](https://github.com/deafps/)
[https://github.com/deafps/SharpTimer](https://github.com/deafps/SharpTimer)

**Comment by Kjerne** [comment]
oh thats very sad

> I think that's the least of the problems. The owner and the project have completely disappeared https://github.com/deafps/ https://github.com/deafps/SharpTimer

**Comment by Mr-Robot-ops** [comment]
> oh thats very sad
> 
> > I think that's the least of the problems. The owner and the project have completely disappeared https://github.com/deafps/ https://github.com/deafps/SharpTimer

Twitter and Twitch account is also gone. I don't think he'll be back. That is really very sad.

**Comment by Mr-Robot-ops** [comment]
He's back again
[https://github.com/deafps/SharpTimer](https://github.com/deafps/SharpTimer)
“This Project is discontinued. Feel free to fork it and build upon it.”
