### ISSUE TITLE
[Bug]: cs2-modded-server-csgo start success connent fail !

### ISSUE THREAD

**Issue by 986823307** [kus/cs2-modded-server#109]
### Server is up to date

- [X] My server is up-to-date and I'm using the latest version of this mod from this github.

### I've followed the instructions

- [X] I've followed the instructions

### Game Server Login Token

- [X] I'm using a valid Game Server Login Token or running on LAN

### Operating System

Windows 11

### Which mod are you playing

Competitive, Deathmatch, Wingman, 1v1, Practice, Surf, Bhop, KZ, Other (please specify)

### Are you trying to host online or on LAN?

Online off a machine on my local network

### Metamod:Source Version

1.11.0-dev+1148

### Metamod:Source Plugins loaded

[01] SourceMod (1.11.0.6936) by AlliedModders LLC   [02] CSGO-ArmsFix (1.0) by Kyle (4y)   [03] CS Tools (1.11.0.6936) by AlliedModders LLC   [04] SDK Tools (1.11.0.6936) by AlliedModders LLC   [05] DHooks (1.11.0.6936) by AlliedModders LLC   [06] SDK Hooks (1.11.0.6936) by AlliedModders LLC   [07] PTaH (1.1.4-b3a9ea6) by Phoenix

### CounterStrikeSharp Version

no

### CounterStrikeSharp Plugins loaded

no

### What is the bug

The server starts up normally, but it keeps prompting to upgrade the server. I've made sure it's up to date and tried to restart it several times. The old csgo version connent keeps time-out, Port I modified 27025 in win.ini

### Game console output

```shell
Connecting to public(120.41.141.236:27025) ...
Retrying public(120.41.141.236:27025) ...
Retrying public(120.41.141.236:27025) ...
Retrying public(120.41.141.236:27025) ...
Retrying public(120.41.141.236:27025) ...
Retrying public(120.41.141.236:27025) ...
Retrying public(120.41.141.236:27025) ...
Retrying public(120.41.141.236:27025) ...
Retrying public(120.41.141.236:27025) ...
Retrying public(120.41.141.236:27025) ...
Retrying public(120.41.141.236:27025) ...
Retrying public(120.41.141.236:27025) ...
Retrying public(120.41.141.236:27025) ...
Retrying public(120.41.141.236:27025) ...
Retrying public(120.41.141.236:27025) ...
Retrying public(120.41.141.236:27025) ...
Retrying public(120.41.141.236:27025) ...
Retrying public(120.41.141.236:27025) ...
Retrying public(120.41.141.236:27025) ...
Retrying public(120.41.141.236:27025) ...
Retrying public(120.41.141.236:27025) ...
Retrying public(120.41.141.236:27025) ...
Retrying public(120.41.141.236:27025) ...
Retrying public(120.41.141.236:27025) ...
Retrying public(120.41.141.236:27025) ...
Retrying public(120.41.141.236:27025) ...
Retrying public(120.41.141.236:27025) ...
Retrying public(120.41.141.236:27025) ...
Retrying public(120.41.141.236:27025) ...
Retrying public(120.41.141.236:27025) ...
Certificate expires in 12h59m at 1716540627 (current time 1716493839), will renew in 10h59m
Connection failed after 30 retries.
```

### Server log output

```shell
Connection to Steam servers successful.
   Public IP is 120.41.141.236.
Assigned persistent gameserver Steam ID [G:1:11567671].
Gameserver logged on to Steam, assigned identity steamid:85568392931607095
Set SteamNetworkingSockets P2P_STUN_ServerList to '103.28.54.173:3478' as per SteamNetworkingSocketsSerialized
VAC secure mode is activated.
GC Connection established for server version 1575, instance idx 1
MasterRequestRestart
Your server is out of date.  Please update and restart.
```

**Comment by mavproductions** [comment]
@986823307 

All your ports forwarded? 

Your server is also requiring an update, based on your last line in the code block. Make sure all your environment variables are set properly for your IP and ports.

**Comment by 986823307** [comment]
I tried it out following the post below and it worked
https://www.reddit.com/r/GlobalOffensive/comments/1b9kf0x/comment/kws4lfo/
