### ISSUE TITLE
[Bug]: Server crashes when starting after new update

### ISSUE THREAD

**Issue by RennieSs** [kus/cs2-modded-server#110]
### Server is up to date

- [X] My server is up-to-date and I'm using the latest version of this mod from this github.

### I've followed the instructions

- [X] I've followed the instructions

### Game Server Login Token

- [X] I'm using a valid Game Server Login Token or running on LAN

### Operating System

Windows 11

### Which mod are you playing

No mod

### Are you trying to host online or on LAN?

Online off a machine on my local network

### Metamod:Source Version

Source version 2.0.0-dev+1291

### Metamod:Source Plugins loaded

Listing 1 plugin:   [01] CounterStrikeSharp (v0 @ 9a221b4) by Roflmuffin

### CounterStrikeSharp Version

v227 (1.0.227+9a221b4)

### CounterStrikeSharp Plugins loaded

css_plugins list   List of all plugins currently loaded by CounterStrikeSharp: 6 plugins loaded.   [#1:LOADED]: "CS2Rcon" (1.2.0) by LordFetznschaedl     Allows for server commands to be executed from the client using !rcon   [#2:LOADED]: "CS2_ExecAfter" (1.0.0) by Kus (https://github.com/kus)     Executes a command after server event or a delay. exec_after for help   [#3:LOADING]: "GameModeManager" (1.0.1) by Striker-Nick     A simple plugin/module that dynamically updates any maplist.txt file based on the current mapgroup.   [#4:LOADED]: "[Custom] Map Configurator" (V. 1.0.2 [Beta]) by Manifest @Road To Glory     Allow server owners to easily create unique configuration files on a per map basis.   [#5:LOADED]: "RockTheVote" (1.8.5) by abnerfs     https://github.com/abnerfs/cs2-rockthevote   [#6:LOADING]: "SimpleAdmin" (0.1.2)

### What is the bug

These options are from some updates ago, and might be a little inaccurate.

When starting the server, it opens the cs2 terminal, and then crashes right after.

Wasnt a problem yesterday. It all happened after tonihgts update

**Comment by kus** [comment]
Yep, was after the last CS2 update. CounterStrikeSharp just pushed an update to fix it, which I have put in the repo.

See the latest update [v1.0.34](https://github.com/kus/cs2-modded-server/releases/tag/v1.0.34)

**Comment by mavproductions** [comment]
@RennieSs expect this to be common after valve does updates (especially major ones) to CS2.

**Comment by RennieSs** [comment]
Alright thank you! I will install the latest update later today!

**Comment by kus** [comment]
@RennieSs is it working now for you?

**Comment by RennieSs** [comment]
Hi! Yes, i installed v1.0.35, and it is working! Ty
