### ISSUE TITLE
[Bug]: Dockerfile clone bug

### ISSUE THREAD

**Issue by WangChuDi** [kus/cs2-modded-server#132]
### Server is up to date

- [X] My server is up-to-date and I'm using the latest version of this mod from this github.

### I've followed the instructions

- [X] I've followed the instructions

### Game Server Login Token

- [X] I'm using a valid Game Server Login Token or running on LAN

### Operating System

Linux Other (please specify)

### Which mod are you playing

No mod

### Are you trying to host online or on LAN?

Online on a cloud host Google, AWS, Azure etc (please specify host), LAN off my machine

### Metamod:Source Version

1

### Metamod:Source Plugins loaded

1

### CounterStrikeSharp Version

1

### CounterStrikeSharp Plugins loaded

1

### What is the bug

The Dockerfile clone the wrong repository in line 38.
`RUN git clone https://github.com/DanielDKnudsen/cs2-modded-server`
which make the fix of install_docker.sj doesnt work.

**Comment by ReneRebsdorf** [comment]
fyi for anyone reading, this was fixed by [this commit](https://github.com/kus/cs2-modded-server/commit/0c32982e9e0cffd3fd0987e1615394cfd8374acc) 4 days ago
