### ISSUE TITLE
[Bug]: Always output this warning message:"Long frame (WarmupPeriod)", and frequently drop frames during play.

### ISSUE THREAD

**Issue by 986823307** [kus/cs2-modded-server#136]
### Server is up to date

- [X] My server is up-to-date and I'm using the latest version of this mod from this github.

### I've followed the instructions

- [X] I've followed the instructions

### Game Server Login Token

- [X] I'm using a valid Game Server Login Token or running on LAN

### Operating System

Windows 11

### Which mod are you playing

No mod

### Are you trying to host online or on LAN?

LAN off a machine on my local network

### Metamod:Source Version

Source version 2.0.0-dev+1293

### Metamod:Source Plugins loaded

Listing 1 plugin:   [01] CounterStrikeSharp (v0 @ 2eaf7c2) by Roflmuffin

### CounterStrikeSharp Version

CounterStrikeSharp was created and is maintained by Michael "roflmuffin" Wilson.   Counter-Strike Sharp uses code borrowed from SourceMod, Source.Python, FiveM, Saul Rennison, source2gen and CS2Fixes.   See ACKNOWLEDGEMENTS.md for more information.   Current API Version: v242 (1.0.242+2eaf7c2)

### CounterStrikeSharp Plugins loaded

 List of all plugins currently loaded by CounterStrikeSharp: 9 plugins loaded.   
[#1:LOADED]: "Custom Votes" (1.0.1) by imi-tat0r     Allows you to create custom votes for your server.  
[#2:LOADED]: "CS2 Announcement Broadcaster" (0.3.0) by Lengran     A plugin that helps server admins to broadcast announcements to users. https://github.com/lengran/CS2AnnouncementBroadcaster  
[#3:LOADED]: "CS2Rcon" (1.2.0) by LordFetznschaedl     Allows for server commands to be executed from the client using !rcon   
[#4:LOADED]: "CS2_ExecAfter" (1.0.0) by Kus (https://github.com/kus)     Executes a command after server event or a delay. exec_after for help   
[#5:LOADED]: "GameModeManager" (1.0.4) by Striker-Nick     A simple plugin to help administrators manage custom game modes, settings, and map rotations.   
[#6:LOADED]: "[Custom] Map Configurator" (V. 1.0.2 [Beta]) by Manifest @Road To Glory     Allow server owners to easily create unique configuration files on a per map basis.   
[#7:LOADED]: "RockTheVote" (1.8.5) by abnerfs     https://github.com/abnerfs/cs2-rockthevote   
[#8:LOADED]: "SimpleAdmin" (0.1.2)   
[#9:LOADED]: "WeaponPaints" (2.5a) by Nereziel & daffyy     Skin, gloves, agents and knife selector, standalone and web-based Certificate expires in 40h36m at 1719108487 (current time 1718962316), will renew in 38h36m

### What is the bug

Always output this warning message, and frequently drop frames during play.
![屏幕截图 2024-06-21 173257](https://github.com/kus/cs2-modded-server/assets/56620683/b43549c5-0287-4f5a-8a9c-d396f038c459)

### Server log output

```shell
289.031250 Long frame (WarmupPeriod): 30.54ms elapsed, 0.18ms sim time, 1 ticks, 18498..18498.
289.109375 Long frame (WarmupPeriod): 29.73ms elapsed, 0.33ms sim time, 1 ticks, 18503..18503.
289.859375 Long frame (WarmupPeriod): 21.11ms elapsed, 0.12ms sim time, 1 ticks, 18551..18551.
291.781250 Long frame (WarmupPeriod): 29.58ms elapsed, 0.17ms sim time, 1 ticks, 18674..18674.
312.453125 Long frame (WarmupPeriod): 29.50ms elapsed, 0.19ms sim time, 1 ticks, 19997..19997.
```

### Steps to reproduce

1.Start the server
2.Start output "Long frame"

**Comment by mavproductions** [comment]
See [this commit](https://github.com/kus/cs2-modded-server/commit/b95339cfa06d8eec1adfd209a2630b36ca135744) @986823307 

Add the following - as it wasn't present at the time of the commit post.
`.*Long frame (WarmupPeriod).*`
`.*Long frame (FreezePeriod).*`

**Comment by mavproductions** [comment]
If the first reply I gave doesn't work, please try:
`^\d*\.?\d*\sLong frame \(WarmupPeriod\).*`
`^\d*\.?\d*\sLong frame \(FreezePeriod\).*`

**Comment by 986823307** [comment]
> If the first reply I gave doesn't work, please try: `^\d*\.?\d*\sLong frame \(WarmupPeriod\).*` `^\d*\.?\d*\sLong frame \(FreezePeriod\).*`

Thanks,it's work.
