### ISSUE TITLE
[Feature]: Unraid docker

### ISSUE THREAD

**Issue by rodaN90** [kus/cs2-modded-server#170]
### Information

Make this available as an unraid docker app.
It isn't in the appstore yet.

Trying to use "docker-compose" just gives me an error "unable to get image 'https://github.com/kus/cs2-modded-server.git': Error response from daemon: invalid reference format" or something like file not found or no account/access.

I don't want to run a VM just to use this repo for hosting a single server.

Maybe I do something wrong and someone can explain me how to set this up in "Unraid"?

Thanks.

**Comment by phyzical** [comment]
@rodaN90 https://github.com/kus/cs2-modded-server/pull/174

i run in unraid, give the readme update a try

**Comment by rodaN90** [comment]
> @rodaN90 #174
> 
> i run in unraid, give the readme update a try

I deinstalled everything and tried from scratch.

I don't know what to do with the commands above "build yourself".

Following the "build yourself" steps, it loads the git data, installs and tries to start. But I get the error "can't find ip address" or something like that.

I also can't find the folder where it installed.

I'm pretty new to linux and unraid. Every other docker I installed, worked perfectly by just using the internal app store or the docker compose file. But it doesn't work with repo. :(

Could you please provide a step by step tutorial on how to get this working on unraid?

**Comment by rodaN90** [comment]
I got it working. A firewall rule on my router was blocking the request to get the IP. After disabling that rule it successfully installed.

But still it's far from working.

I can't modify files or create the folders in "custom_files" so I can copy over files like "admins.json" since I'm missing permissions.
![Screenshot 2025-01-08 235510](https://github.com/user-attachments/assets/db18db04-8802-4e3a-bf1e-d983de8b9aa7)
![Screenshot 2025-01-08 235645](https://github.com/user-attachments/assets/53336572-b226-4be1-ba1d-69a16ca870a9)

It seems by default it set permissions to: Owner: Read/Write, Group: Read-Only, Other: Read-Only
And the owner for all folders and files is: "UNKNOWN"

In windows it shows as this:
![Screenshot 2025-01-09 000031](https://github.com/user-attachments/assets/eaf3d5b5-64a1-4f7d-ae59-d3b750980289)

The problem now is, if I change the permissions, add my files and start the server... or even change permissions back to what it was and then start the server -> It doesn't start and the docker crashes.

Docker log:
![Screenshot 2025-01-09 000301](https://github.com/user-attachments/assets/2517e023-0b19-4ff1-bb54-cb6f179b85b5)

Terminal Docker log:
![Screenshot 2025-01-09 000729](https://github.com/user-attachments/assets/91000a25-77ea-4002-86ab-50f882cf7609)

The files (in custom_files) got copied over but fails to start the server.

When I don't try to get the custom files working, I can restart the docker without a problem and the server starts normaly.

The only way I can start the server again after fumbling with custom files is by deleting all folders and the docker+image and start from scratch. But that way I can't use any modified configs. :/

Also how can I access that "/home/steam" folder it creates?
When I use the terminal with "ls" or "dir" it doesn't show any content in the home folder?

**Comment by phyzical** [comment]
@rodaN90 you should have 2 folders that get mounted.

It looks like you have combined the folders then mounted both?

blatt it all have just 2 folders custom_files and cs2.

Mount both of those and your custom_files will persist

the cs2 folder will be blatted/updated as new updates are released

when it launches it automatically copies the custom_files for you

https://github.com/kus/cs2-modded-server/blob/master/install_docker.sh#L144

**Comment by rodaN90** [comment]
@phyzical 
Sorry, I'm pretty new to linux, unraid and docker.

I don't understand what you mean with your first question?
I did the setup as stated in the 3rd answer from Shakanuga. No extra commands were used.

And is "blatt" just a term for delete?

I did it this way now:
![Screenshot 2025-01-09 180013](https://github.com/user-attachments/assets/f9fc05b0-ba27-427d-bee6-27cc4216dc5f)

Instead of:
/mnt/user/appdata/CS2 Server/
/mnt/user/appdata/CS2 Server/custom_files

That way it fixed the permission error. I can use the custom_files folder now without changing permissions/owner.

I also found the problem why the server wouldn't start after adding custom files.
I had changed the "core.json" in  "Z:\CS2 Server\custom_files\addons\counterstrikesharp\configs" and added the following:

```
"PluginHotReloadEnabled": true,
"PluginAutoLoadEnabled": true,
"ServerLanguage": "en",
"UnlockConCommands": true,
"UnlockConVars": true
```
After deleting those lines the server starts normally.
I guess one of those commands is broken and made the server crash.

But it's finally working now. I can add files via SMB in windows and they get copied over. Also I can stop/start the server how often I want without crashing.

Final questions:

When I stop the docker via GUI:
![Screenshot 2025-01-09 180626](https://github.com/user-attachments/assets/0c1efbc1-c092-4a1d-b8e9-3aa3efb7316b)

and start the server via GUI. It does auto-update the server AND the plugins + new addons, cfgs, ect.? So basically I never have to take care of updating or checking for newer version of plugins or anything?

2nd question:
The readme said something about a cron-job to restart the server once daily to update in case of a cs2 update.
How do I do that? Is there maybe a simple plugin for unraid to manage that stuff?

But all in all thanks for the fast responses and great help!
Learned alot about unraid and docker and how to set it up. :)

**Comment by phyzical** [comment]
> and start the server via GUI. It does auto-update the server AND the plugins + new addons, cfgs, ect.? So basically I never have to take care of updating or checking for newer version of plugins or anything?



In most cases yes, it will just redownload the core server on cs2 updates on each container boot. i have a cron to reboot the container once a day so that it "attempts" to stay up to date. there was mention of leveraging something like systemd to have the container autoinit a server update without the container being rebooted, but rebooting the container works for me.  if it does fail to boot, you can just remove the `/mnt/user/appdata/CS2 Server/steam/cs2` folder contents and it will just fresh redownload. 

The plugin versions are stored inside the docker container and copied across for you, so as you install new image versions it will update those.

> 2nd question: The readme said something about a cron-job to restart the server once daily to update in case of a cs2 update. How do I do that? Is there maybe a simple plugin for unraid to manage that stuff?

just install the userscripts plugin, create a new script, have it run once a day

```
#!/bin/bash

docker restart CS2-Server
```

> 
> 3rd question: How can I access the "/home/steam" folder? Nothing shows in unraid terminal with "ls" or "dir"?
> 

for performing ls on debian for some reason it need the interactive flag -i, i think by default unraid doesn't provide that?

try
```
docker exec -it CS2-Server /bin/bash
```
![image](https://github.com/user-attachments/assets/628ef259-8242-4ab4-8805-5d1f54c3fad1)
