### ISSUE TITLE
[Bug]: Docker Container

### ISSUE THREAD

**Issue by simonzander** [kus/cs2-modded-server#172]
### Server is up to date

- [X] My server is up-to-date and I'm using the latest version of this mod from this github.

### I've followed the instructions

- [X] I've followed the instructions

### Game Server Login Token

- [X] I'm using a valid Game Server Login Token or running on LAN

### Operating System

Linux Ubuntu 22.04

### Which mod are you playing

Other (please specify)

### Are you trying to host online or on LAN?

Online off my machine

### Metamod:Source Version

na

### Metamod:Source Plugins loaded

na

### CounterStrikeSharp Version

na

### CounterStrikeSharp Plugins loaded

na

### What is the bug

Hi after a fresh docker installation the steamcmd fails with no permission to the directory.

`Connecting anonymously to Steam Public...OK

Waiting for client config...OK

Waiting for user info...OK

ERROR! Failed to install app '730' (Missing file permissions)

/home/user !!!!!!!

Installing mods

Merging in custom files

grep: game/csgo/gameinfo.gi: No such file or directory

game/csgo/gameinfo.gi successfully patched for Metamod.

Starting server on 81.169.194.72:

./game/bin/linuxsteamrt64/cs2 -dedicated -console -usercon -autoupdate -tickrate 128 -port +map de_dust2 -maxplayers 16 -authkey "EC35663049D0C22F8C691BCE8002A637" +sv_setsteamaccount "A17B5DB073F761EDF6DBFF3D259A42C3" +game_type 0 +game_mode 0 +mapgroup mg_active +sv_lan +sv_password +rcon_password +exec

awk: cannot open game/csgo/gameinfo.gi (No such file or directory)

sudo: /home/steam/cs2/game/bin/linuxsteamrt64/cs2: command not found`

### Steps to reproduce

1. build docker image on server
2. start with docker compose
3. error occurs.

**Comment by phyzical** [comment]
https://github.com/kus/cs2-modded-server/pull/147
