### ISSUE TITLE
[Bug]: CT default gloves not rendering

### ISSUE THREAD

**Issue by 0x111** [kus/cs2-modded-server#24]
### Server is up to date

- [X] My server is up-to-date and I'm using the latest version of this mod from this github.

### I've followed the instructions

- [X] I've followed the instructions

### Game Server Login Token

- [X] I'm using a valid Game Server Login Token or running on LAN

### Operating System

Linux Ubuntu 18.04

### Which mod are you playing

No mod

### Are you trying to host online or on LAN?

Online off my machine

### Metamod:Source Version

1.11.0-dev+1148

### Metamod:Source Plugins loaded

[01] SourceMod (1.11.0.6931) by AlliedModders LLC   [02] CSGO-ArmsFix (1.0) by Kyle (4y)   [03] CS Tools (1.11.0.6931) by AlliedModders LLC   [04] SDK Tools (1.11.0.6931) by AlliedModders LLC   [05] SDK Hooks (1.11.0.6931) by AlliedModders LLC   [06] DHooks (1.11.0.6931) by AlliedModders LLC

### SourceMod Version

1.11.0.6931

### SourceMod Plugins loaded

[SM] Listing 24 plugins:   01 "Fun Commands" (1.11.0.6931) by AlliedModders LLC   02 "Map configs" (1.3) by Berni   03 "Fix Hint Color Messages" (1.2.2 Franc1sco franug github version) by Phoenix (˙·٠●Феникс●٠·˙)   04 "Admin File Reader" (1.11.0.6931) by AlliedModders LLC   05 "Basic Info Triggers" (1.11.0.6931) by AlliedModders LLC   06 "Player Commands" (1.11.0.6931) by AlliedModders LLC   07 "Anti-Flood" (1.11.0.6931) by AlliedModders LLC   08 "Reconnect Players" (1.0) by Ilusion9   09 "Reserved Slots" (1.11.0.6931) by AlliedModders LLC   10 "Fun Votes" (1.11.0.6931) by AlliedModders LLC   11 "Command Time-Traveler" (1.2.0) by DarthNinja   12 "Nextmap" (1.11.0.6931) by AlliedModders LLC   13 <Failed> "Weapons & Knives" (1.7.7) by kgns | oyunhost.net   14 "Admin Help" (1.11.0.6931) by AlliedModders LLC   15 "Client Preferences" (1.11.0.6931) by AlliedModders LLC   16 "Basic Comm Control" (1.11.0.6931) by AlliedModders LLC   17 "Sound Commands" (1.11.0.6931) by AlliedModders LLC   18 "CSGOFixes" (2.0) by Vauff + xen   19 "Basic Ban Commands" (1.11.0.6931) by AlliedModders LLC   20 "Basic Commands" (1.11.0.6931) by AlliedModders LLC   21 "Basic Votes" (1.11.0.6931) by AlliedModders LLC   22 "Admin Menu" (1.11.0.6931) by AlliedModders LLC   23 "Basic Chat" (1.11.0.6931) by AlliedModders LLC   24 "Gloves" (1.0.5) by kgns | oyunhost.net

### What is the bug

The default ct gloves are not rendering for me in-game.

See screenshot

![image](https://github.com/kus/csgo-modded-server/assets/34659520/28139d47-91d3-45dd-ba4c-e39e260cdeea)

### Server log output

```shell
Late precache of models/weapons/v_models/arms/glove_hardknuckle/v_glove_hardknuckle.mdl
[AI BT]: Required key 'config' missing from KV3 file.[AI BT]: Unable to load behavior tree 'scripts/ai/deathmatch/bt_config.kv3', bot skill = 'profile level 1'
[AI BT]: Required key 'config' missing from KV3 file.[AI BT]: Unable to load behavior tree 'scripts/ai/deathmatch/bt_config.kv3', bot skill = 'profile level 0.9'
```

### Steps to reproduce

1. Install server using install.sh
2. Connect to server
3. You start on dust2, pick CT side and if the current player has default gloves these are not showing up
4. non-default gloves are rendering fine

**Comment by kus** [comment]
As CS2 is out now I'm not looking at issues on CS:GO anymore
