### ISSUE TITLE
[Feature]: [Bug]: ERROR: Cannot retrieve your public IP address...

### ISSUE THREAD

**Issue by HexMr** [kus/cs2-modded-server#29]
### Information

Hello, my system version is Debian 12. I have a problem when I run the start.sh file, nothing is displayed for a while and then after some time I receive the error "ERROR: Cannot retrieve your public IP address...". My network is configured according to the instructions, so I don't understand what the problem is. Please help and do not close the thread, if you need any additional information, I will be happy to provide it. 
My server is up-to-date and I'm using the latest version of this mod from this github.
I've followed the instructions .
I'm using a valid Game Server Login Token or running on LAN
Are you trying to host online or on LAN: Online off my machine

**Comment by kus** [comment]
I specifically have issue templates setup so you fill out the form when you have a bug, and I told you in your last ticket to lodge it as a bug so you fill out the form yet you still log it as a feature when it's a bug to avoid filling out a form.

As root (`sudo su`) download the latest install script (`cd / && curl -s -H "Cache-Control: no-cache" -o "install.sh" "https://raw.githubusercontent.com/kus/cs2-modded-server/master/install.sh" && chmod +x install.sh`) on the server and make sure it is the latest (`cat install.sh`) and run it.

If you have any errors give me the console output.

**Comment by kus** [comment]
Closing due to no response, so assuming it's fixed.

**Comment by HexMr** [comment]
Hello, I had a lot of things at work, first of all, could you send me an example configured start.sh file? I'm not sure if I configured this file correctly. Secondly, after configuring the start.sh file, it no longer displays this error, but displays something else, so I don't really know what to do. 
![Bez tytułu](https://github.com/kus/cs2-modded-server/assets/104520373/e52db0ea-3d93-416a-a4ad-bfda485c3ee1)
I have an updated operating system.

**Comment by kus** [comment]
You seem to have lots of issues with updating your OS which is nothing to do with my script.

This command is what is returning errors:

`apt-get update -y && apt-get upgrade -y`

On your machine run that command and troubleshoot why it’s not working. That’s outside the support of this mod.

Once you resolve that, [here](https://github.com/kus/cs2-modded-server#running-on-linux) is the specific part of my documentation with full instructions on how to run the script.

**Comment by HexMr** [comment]
I entered the command you wrote, but the error still occurs, I don't know what causes it, the network is definitely configured correctly.
https://i.imgur.com/klDrHEi.png

**Comment by kus** [comment]
Please reread what I wrote.

**Comment by HexMr** [comment]
This is probably due to the fact that I once made changes to the /etc/apt/sources.list file because I wanted to update the system, how to restore the default file? I searched the Internet but couldn't find it, I tried to copy the file according to the guide from this forum, but it didn't work, how to restore the default value of the sources.list file?

**Comment by HexMr** [comment]
I know that this goes beyond the support of this mod, but you certainly know Linux better than me, that's why I'm asking for help, because I don't know how to restore the default values for this file.

**Comment by HexMr** [comment]
Okay, I managed to restore this file, the server is downloading

**Comment by HexMr** [comment]
@kus When I run install.sh I get the message "The operating system distribution is not supported. Debian GNU/linux 12"

**Comment by kus** [comment]
If you want any help, post the full server console output.

Are you sure you are using the latest install.sh because I added Debian is supported.

I tested the script on a brand new Debian 12 VM.

**Comment by kus** [comment]
You should see this in the install.sh script.

```
elif [[ $DISTRO_OS == Debian* ]]; then
	if [ "${DISTRO_VERSION}" == "10" ]; then
		apt-get install -y dnsutils curl wget screen nano file tar bzip2 gzip unzip hostname bsdmainutils python3 util-linux xz-utils ca-certificates binutils bc jq tmux netcat-traditional lib32stdc++6 libsdl2-2.0-0:i386 distro-info lib32gcc1 >/dev/null
	elif [ "${DISTRO_VERSION}" == "11" ]; then
		apt-get install -y dnsutils curl wget screen nano file tar bzip2 gzip unzip hostname bsdmainutils python3 util-linux xz-utils ca-certificates binutils bc jq tmux netcat-traditional lib32stdc++6 libsdl2-2.0-0:i386 distro-info lib32gcc-s1 >/dev/null
	elif [ "${DISTRO_VERSION}" == "12" ]; then
		apt-get install -y dnsutils curl wget screen nano file tar bzip2 gzip unzip hostname bsdmainutils python3 util-linux xz-utils ca-certificates binutils bc jq tmux netcat-traditional lib32stdc++6 libsdl2-2.0-0:i386 distro-info lib32gcc-s1 >/dev/null
	elif [ "${DISTRO_VERSION}" == "13" ]; then
		apt-get install -y dnsutils curl wget screen nano file tar bzip2 gzip unzip hostname bsdmainutils python3 util-linux xz-utils ca-certificates binutils bc jq tmux netcat-traditional lib32stdc++6 libsdl2-2.0-0:i386 distro-info lib32gcc-s1 >/dev/null
	else
		echo "$DISTRO_OS: $DISTRO_VERSION not officially supported; using Debian 13 config"
		apt-get install -y dnsutils curl wget screen nano file tar bzip2 gzip unzip hostname bsdmainutils python3 util-linux xz-utils ca-certificates binutils bc jq tmux netcat-traditional lib32stdc++6 libsdl2-2.0-0:i386 distro-info lib32gcc-s1 >/dev/null
	fi
else
```

**Comment by HexMr** [comment]
@kus Installing the latest version of instal.sh helped, I have one more question, firstly I don't understand how to change the server name, it is usually done in the server.cfg file, but I don't see anything there and I have a second question, because I forgot to specify it in the start.sh file server port, where I can change the port on which the server runs, because the IP address will be the permanent address of my machine. I know you gave instructions on how to change the server name, but I don't fully understand it, so if you could help me with these two issues, I would be very grateful.

**Comment by kus** [comment]
You should only be starting the server from `install.sh` as it keeps the server updated and updated with the git repo and merges the custom files in.

To change the server name read [this](https://github.com/kus/cs2-modded-server?tab=readme-ov-file#custom-files) on "custom files" you can look at what I use on my server as an example in the `custom_files_example` folder.

The simple answer is, create this file `custom_files/cfg/custom_all.cfg` and put `hostname "My CS Server"` in it.

To change PORT you set an [environment variable](https://github.com/kus/cs2-modded-server?tab=readme-ov-file#environment-variables) when running the script as per the [instructions](https://github.com/kus/cs2-modded-server?tab=readme-ov-file#running-on-linux).

As per the [instructions](https://github.com/kus/cs2-modded-server?tab=readme-ov-file#playing-workshop-mapscollections) if you haven't set an `API_KEY` you don't be able to play custom maps.

i.e.:

export RCON_PASSWORD="changeme"
export API_KEY="changeme"
export STEAM_ACCOUNT=""
export SERVER_PASSWORD=""
export PORT="27015"
export TICKRATE="128"
export MAXPLAYERS="32"
cd / && curl --silent --output "install.sh" "https://raw.githubusercontent.com/kus/cs2-modded-server/master/install.sh" && chmod +x install.sh && bash install.sh

**Comment by HexMr** [comment]
I don't fully understand you, the environment variable, in this case the install.sh file, because I can't start the server from the start.sh file. What I mean is that I already downloaded the script, ran the start.sh file and everything downloaded, but I want to change the port because I forgot to set it when running the start.sh file. If you could give me a piece of paper where I can change the port on a ready server, unless from what I understand I have to change the variables in the start.sh file, run it again and the changes will be overwritt

**Comment by HexMr** [comment]
Okay, I actually had to run the start.sh file again and the environment variables were overwritten

**Comment by HexMr** [comment]
But I have a problem in Rcon, when I enter the command in the console it doesn't work, I read that it doesn't work temporarily, so should I use external software to manage Rcon?

**Comment by HexMr** [comment]
I can't find the admins.cfg file in my configuration files, why?

**Comment by kus** [comment]
You can create a bash script to set the variables and run `install.sh` i.e.:

```
export RCON_PASSWORD="changeme"
export API_KEY="changeme"
export STEAM_ACCOUNT=""
export SERVER_PASSWORD=""
export PORT="27015"
export TICKRATE="128"
export MAXPLAYERS="32"
cd / && bash install.sh
```

Do you mean `admins.json`? There is no `admins.cfg`.

Again, look at my `custom_files_example` folder for an example how I configure my server.

**Comment by HexMr** [comment]
I mean the configuration file for rcon to give yourself permissions, or is it the admin.joson file located in this wipe? /cs2-modded-server-master/game/csgo/cfg/MatchZy
If it is this file, could you give me an example of its configuration? Because the documentation of the Rcon mod itself is quite poor

**Comment by HexMr** [comment]
@kus

**Comment by kus** [comment]
Look at the example `custom_files_example` folder which is literally the only changes I make for my server.

Admins are defined in custom_files_example/addons/counterstrikesharp/configs/

My user has full admin rights.

All the plugins use those permissions.

So once you add yourself you can use !RCON say hi in game

Do some debugging for custom_all.cfg is it getting put in the right place on your server? Add an echo “custom_all.cfg executed” and look for it in the server console. If it’s not there you are putting it in the wrong folder.

**Comment by HexMr** [comment]
@kus 
![githuin](https://github.com/kus/cs2-modded-server/assets/104520373/d8989a64-4bb9-4ee5-a281-dc78eedb914b)
From what I understand, the file is there, here's proof that I have such a file created
![github2](https://github.com/kus/cs2-modded-server/assets/104520373/6ec4ec20-7325-4b5f-b6bf-1adc5a83c683)
and this is the content of this file
![notepad](https://github.com/kus/cs2-modded-server/assets/104520373/115f50a0-2516-4059-80db-09269cec1b3d)

**Comment by kus** [comment]
As per the instructions you need custom files in `custom_files` not `custom_files_example`. `custom_files_example` is as the name suggests, an example.

rename it and take _example off the end.

**Comment by HexMr** [comment]
![alg1](https://github.com/kus/cs2-modded-server/assets/104520373/c586bca1-b1dc-47e8-8d4a-cdb3ba3d8014)
![alg2](https://github.com/kus/cs2-modded-server/assets/104520373/f6b7e012-7656-4c3e-9723-787e53d72941)
![alg3](https://github.com/kus/cs2-modded-server/assets/104520373/7e8dc404-ff4e-4949-a9df-140b5a7d2ff3)
![alg4](https://github.com/kus/cs2-modded-server/assets/104520373/3b847dbf-4945-4688-a977-01e538c19892)
@kus It still doesn't work

**Comment by kus** [comment]
Showing me cs2-modded-server-master tells me you didn’t follow the instructions (which is apparent from all the questions you have asked me)

Read the instructions step by step for Linux. You never upload the zip file. 

The config you are showing me has old admin stuff in it too.

Start again, read the instructions. I can’t make it any easier for people.

Run install.sh

In the /home/steam/cs2 folder you put your custom_files files you want to merge in. Run install.sh again. That is it

**Comment by HexMr** [comment]
@kus Should I just run install.sh in an empty folder? I don't quite understand what you mean. I've read the instructions but I still don't understand what you mean, could you explain step by step what I should do? I didn't put any files in this folder, I ran install.sh again but it didn't help, please explain what to do.

**Comment by HexMr** [comment]
@kus 
![image](https://github.com/kus/cs2-modded-server/assets/104520373/9274d00a-b24a-4f28-a96a-4a6e16ac311f)
I did everything according to the instructions, but the server name still does not change

**Comment by kus** [comment]
`cs2-modded-server-master1` no you didn't. You uploaded the zip again.

Let me break this command down for you from the instructions:
```
sudo su
export RCON_PASSWORD="changeme"
export API_KEY="changeme"
export STEAM_ACCOUNT=""
export SERVER_PASSWORD=""
export PORT="27015"
export TICKRATE="128"
export MAXPLAYERS="32"
cd / && curl --silent --output "install.sh" "https://raw.githubusercontent.com/kus/cs2-modded-server/master/install.sh" && chmod +x install.sh && bash install.sh
```

`sudo su` Change user to root
`export RCON_PASSWORD...` Set environment variables
`cd /` Change to the root directory `/`
`curl --silent --output "install.sh" "https://raw.githubusercontent.com/kus/cs2-modded-server/master/install.sh"` Download the latest `install.sh`
`chmod +x install.sh` Add execute permissions to the script
`bash install.sh` Run the script *FROM THE ROOT DIRECTORY*

When the script finishes running it should have downloaded everything to `/home/steam/cs2/`

Inside there you should see a folder `custom_files` *THIS IS WHERE YOU PUT YOUR CUSTOM FILES YOU WANT TO MERGE INTO THE SERVER*

So in your scenario this file should exist `/home/steam/cs2/custom_files/cfg/custom_all.cfg` *IF IT IS NOT THIS PATH IT WILL NOT WORK*

Once you have your files in there you run the `install.sh` script again, from the root folder.

**Comment by HexMr** [comment]
![image](https://github.com/kus/cs2-modded-server/assets/104520373/0feda6ee-e374-4109-9710-775ecf3d32fe)
Now I have a different problem, the first time the server started normally, and now I have this error
@kus

**Comment by kus** [comment]
That's a problem with your server.

Try restart your server/VM.

**Comment by HexMr** [comment]
![image](https://github.com/kus/cs2-modded-server/assets/104520373/beccdca0-2401-4c95-88e2-2f439822e54e)
![image](https://github.com/kus/cs2-modded-server/assets/104520373/efab893a-d32b-4e57-881a-56a619cfec93)
Changing the server name still doesn't work, I start the server via the install.sh file
@kus

**Comment by kus** [comment]
/CS2/ is not the correct directory.

Do you have SSH on the server?

SSH onto the server and `sudo su`

`cd /`

`ls -lah` send me the output

`cd /home/steam/cs2`

`ls -lah` send me the output

**Comment by HexMr** [comment]
![image](https://github.com/kus/cs2-modded-server/assets/104520373/656447a6-0065-4446-8a95-a15fdeed717c)
![image](https://github.com/kus/cs2-modded-server/assets/104520373/2093f17a-2d63-4911-b9ef-23f1a2cec3ff)
Yes, I have ssh and sudo on the machine, I am logged in as root on the machine by default, so I don't need to use sudo.
@kus

**Comment by kus** [comment]
Okay, couple more things:

`cd /home/steam/cs2/custom_files/cfg/`

`cat custom_all.cfg` show me a screenshot of output

`cd /home/steam/cs2/game/csgo/cfg/`

`cat custom_all.cfg` show me a screenshot of output

`cd /`

<SET ENVIRONMENT VARIABLES>

`./install.sh`copy all of the output to here

**Comment by HexMr** [comment]
![image](https://github.com/kus/cs2-modded-server/assets/104520373/9cdf6b34-fa61-4b1b-8ecc-858d7e34ce86)
In my case there is no such directory  cd /home/steam/cs2/game/csgo/cfg/
![image](https://github.com/kus/cs2-modded-server/assets/104520373/0058a931-9544-4869-bf49-1fe3caa4ecb7)

**Comment by HexMr** [comment]
@kus

**Comment by kus** [comment]
I can’t help you if you are modifying the scripts.

You should have a `/home/` folder and a `steam` folder and `steam` user that the script creates.

Maybe try creating a `/home/` folder as the script creates the `steam` user and folder.

**Comment by HexMr** [comment]
Znalazłem folder Steam w katalogu domowym mojej mamy, nie wiem co stworzyło dla mnie drugi serwer CS2. I managed to change the server name, and if I want a different name for each mode, do I have to modify the cfg for each mode?
@kus

**Comment by HexMr** [comment]
And if I want to set up several servers, set a different port for each one (you can't set the port in the install.sh file) @kus

**Comment by kus** [comment]
Yes if you want a different name per mode you set the custom file for each mode like in the example

You can create `ffa.sh` `surf.sh` `dm.sh` for example and set the variables and run `install.sh` in each one.

See my [gcp.sh](https://github.com/kus/cs2-modded-server/blob/master/gcp.sh) script as an example that does this.

**Comment by HexMr** [comment]
@kus Thank you very much for your help, I have a few more questions whether I should add the STEAM_ACCOUNT variable to the file e.g. surf.sh if I want to create a web server (this variable is missing in your example) and the second question is because I can't find it in the documentation with what command rcon did the server mode change?

**Comment by kus** [comment]
Yes you need `STEAM_ACCOUNT` for each server or your server won’t work. You would put it in each file with the rest of the variables. I’m not sure if you can use one for all of them or you need one per server. Test it yourself.

I don’t understand the last question, if you mean how to change the mode you can do it from server console with `exec surf` for example or in game `!rcon exec surf`

`exec mods` to see a list.

**Comment by HexMr** [comment]
I have one more problem, when I want to change the mode from rcon, it shows me that I do not have permissions, and I have added myself to the admin.json file located in this location /home/steam/cs2/custom_files/cfg/MatchZy

**Comment by HexMr** [comment]
@kus

**Comment by kus** [comment]
You need to add yourself to here `custom_files/addons/counterstrikesharp/configs/admins.json`

See my [example](https://github.com/kus/cs2-modded-server/blob/master/custom_files_example/addons/counterstrikesharp/configs/admins.json).

**Comment by HexMr** [comment]
I copied your custom cfg example, what do I need to do in this file? I looked at it, but I don't know what to change there, could you give me an example of the corrected file? @kus

**Comment by kus** [comment]
In identity you need to add your steam id.

Here change Kus to your name, and the number in identity to your SteamID64 number. 

Put your profile url [here](https://steamid.io/lookup/76561197960377828) to find it.

```
{
  "Kus": {
    "identity": "76561197960377828",
    "groups": [
      "#css/admin"
    ]
  }
}
```

**Comment by HexMr** [comment]
@kus ok, I did what you wrote, now I have a different problem, when I enter the command in the chat, nothing is displayed and nothing happens with the server.

**Comment by kus** [comment]
Check the server logs to see if there is errors.

To check everything is working correctly run the following commands in the server console:

`meta list` and you should see CounterStrikeSharp in the output
`css_plugins list` and you should see a few plugins in the output

**Comment by HexMr** [comment]
![image](https://github.com/kus/cs2-modded-server/assets/104520373/42d8db12-ef39-4387-882a-d50c944a974a)
Nothing happens

**Comment by HexMr** [comment]
@kus

**Comment by kus** [comment]
What does it say now?

!rcon say hi

**Comment by HexMr** [comment]
Now I turned on the server and the mod change works, the worse thing is that when I change it to 1v1 it closes the entire server (this doesn't happen with surf mode). The console shows me "memory protection violation".

**Comment by HexMr** [comment]
@kus

**Comment by kus** [comment]
I’ll have a look at 1v1. You can also use deathmatch which is free for all.

1v1 isn’t great yet as there is no mod for it

**Comment by HexMr** [comment]
@kus Thank you very much for your help and support. By the way, I really care about the 1v1 mode, I would like to run this mode on my main IP address. I checked and surf and DM start normally. I just started the DM server on a different IP address.

**Comment by kus** [comment]
Try pull the latest update and let me know if it's fixed

**Comment by HexMr** [comment]
![image](https://github.com/kus/cs2-modded-server/assets/104520373/c3291a27-f999-4ba8-aeea-ebcead74e7ad)
Now the server doesn't start at all, before it got stuck unpacking the server packages or something (I don't remember exactly) and now I have something like this.
@kus

**Comment by kus** [comment]
That’s an issue with your server. Restart it

**Comment by kus** [comment]
If something stops working. Restart your server and try again. If it’s still an issue post it here.

Half of your messages can be fixed by restarting your server and have nothing to do with my repo.

**Comment by HexMr** [comment]
But I start the server from scratch, I have the rest of the servers running in screen, and I run this one directly on the server, without screen. Additionally, on my servers running in the screen, I cannot change the game mode, I type !rcon exec Deathmatch but nothing happens. @kus

**Comment by kus** [comment]
Any issues about sockets or Debian is your server. Do not ask for help here. If other servers work on screen run them all in screen.

https://github.com/kus/cs2-modded-server#changing-game-modes

it’s `!rcon exec dm`

or from server console `exec dm`

**Comment by HexMr** [comment]
![image](https://github.com/kus/cs2-modded-server/assets/104520373/b26030e2-ab61-4ccf-a44b-aa0f453f94e8)
![image](https://github.com/kus/cs2-modded-server/assets/104520373/e4af4dd3-7b92-4811-954e-873478f62eeb)
Rcon still doesn't work

**Comment by kus** [comment]
It says all your plugins are unloaded?
