### ISSUE TITLE
[Feature]: Need Help to get a GunGame(ArmsRace) Server runing

### ISSUE THREAD

**Issue by soko-grafik** [kus/cs2-modded-server#31]
### Information

Hi, 
first off all,  great work @kus thanks for this repo.

We wan´t to play CS2 GunGame(ArmsRace) at a oldschool Lanparty (https://lanpartey.de) ;-). 

With the Help of  your Repo we can run all Servers, but GunGame Server we are stucking.

Do You have any Mod or  Config  to get it run. 

 Thx

**Comment by kus** [comment]
Thank you. At this point in time there is no public arms race/gun game plugins. I’m waiting for them too!

There are two people working on seperate ones, hopefully they release them in the next few week and I will add them into this repo.

When is your lan party?

**Comment by kus** [comment]
@soko-grafik someone has released a GunGame plugin and I've added it to the repo. It works great!
