### ISSUE TITLE
[Bug]:   Cannot retrieve your public IP address...

### ISSUE THREAD

**Issue by Hengsto** [kus/cs2-modded-server#32]
### Server is up to date

- [X] My server is up-to-date and I'm using the latest version of this mod from this github.

### I've followed the instructions

- [X] I've followed the instructions

### Game Server Login Token

- [X] I'm using a valid Game Server Login Token or running on LAN

### Operating System

Linux Ubuntu 22.04

### Which mod are you playing

No mod

### Are you trying to host online or on LAN?

Online on a cloud host Google, AWS, Azure etc (please specify host)

### Metamod:Source Version

none

### Metamod:Source Plugins loaded

none

### CounterStrikeSharp Version

none

### CounterStrikeSharp Plugins loaded

none

### What is the bug

I cant install cuz of the error

### Steps to reproduce

sudo RCON_PASSWORD="XXXX" \
     API_KEY="XXXX" \
     STEAM_ACCOUNT="XXXX" \
     SERVER_PASSWORD="XXXX" \
     PORT="27015" \
     TICKRATE="128" \
     MAXPLAYERS="32" \
     bash -c 'curl --silent "https://raw.githubusercontent.com/kus/cs2-modded-server/master/install.sh" | bash'

**Comment by kus** [comment]
You need to give me the server log output.

What host are you using?

**Comment by kus** [comment]
Closed due to inactivity
