### ISSUE TITLE
[Feature]: Add server whitelist

### ISSUE THREAD

**Issue by joshschools** [kus/cs2-modded-server#39]
### Information

Would like to add a server whitelist function: https://github.com/PhantomYopta/CS2_WhiteList

**Comment by kus** [comment]
Hey @joshschools 

Thanks for adding the module. I merged it in with some tweaks.

I moved it to the disabled folder, as if you have it enabled for everyone who uses this repo no one would be able to get into their server if they don't configure a whitelist.

If you want to enable it on your server just load the plugin by putting this `css_plugins load "plugins/disabled/WhiteList/WhiteList.dll"` in one of your `.cfg` files.

If you want it to load on every mod on your server, you can put it in your `custom_all.cfg` file see [mine](https://github.com/kus/cs2-modded-server/blob/master/custom_files_example/cfg/custom_all.cfg) for an example.

And the whitelist file is located at `/game/csgo/addons/counterstrikesharp/plugins/disabled/WhiteList/whitelist.txt` which you would put in `/custom_files/addons/counterstrikesharp/plugins/disabled/WhiteList/whitelist.txt`so it is not overwritten.

Let me know if you have any troubles.

Thanks
