### ISSUE TITLE
[Bug]: Warning: mapgroup is null!

### ISSUE THREAD

**Issue by BorislavKolev1994** [kus/cs2-modded-server#43]
### Server is up to date

- [X] My server is up-to-date and I'm using the latest version of this mod from this github.

### I've followed the instructions

- [X] I've followed the instructions

### Game Server Login Token

- [X] I'm using a valid Game Server Login Token or running on LAN

### Operating System

Linux Other (please specify)

### Which mod are you playing

Surf

### Are you trying to host online or on LAN?

Online on a game hosting network (please specify host)

### Metamod:Source Version

Metamod:Source version 2.0.0-dev+1278

### Metamod:Source Plugins loaded

[01] CounterStrikeSharp (0.1.0) by Roflmuffin   [02] Movement Unlocker (1.0) by Vauff

### CounterStrikeSharp Version

CounterStrikeSharp was created and is maintained by Michael "roflmuffin" Wilson.   Counter-Strike Sharp uses code borrowed from SourceMod, Source.Python, FiveM, Saul Rennison, source2gen and CS2Fixes.   See ACKNOWLEDGEMENTS.md for more information.   Current API Version: 142

### CounterStrikeSharp Plugins loaded

css_plugins list   List of all plugins currently loaded by CounterStrikeSharp: 8 plugins loaded.   [#1:LOADED]: "Map Chooser" (1.2.6) by Retro - https://insanitygaming.net/     Handles map voting and map changing   [#2:LOADED]: "CS2Rcon" (1.2.0) by LordFetznschaedl     Allows for server commands to be executed from the client using !rcon   [#3:LOADED]: "SharpTimer" (0.1.9 - 1/10/2024 3:18:34 AM) by DEAFPS https://github.com/DEAFPS/     A simple CSS Timer Plugin   [#4:LOADED]: "CS2-Tags" (1.0.3b) by daffyy     Add player tags easily in cs2 game   [#5:LOADED]: "CS2-Ultimate-Mapchooser" (1.0.0) by Kus (https://steamcommunity.com/id/kus/)     The Ultimate Mapchooser for CS2!   [#6:LOADED]: "CS2_ExecAfter" (1.0.0) by Kus (https://github.com/kus)     Executes a command after server event or a delay. exec_after for help   [#7:LOADED]: "[Custom] Map Configurator" (V. 1.0.2 [Beta]) by Manifest @Road To Glory     Allow server owners to easily create unique configuration files on a per map basis.   [#8:LOADED]: "SimpleAdmin" (0.1.2)

### What is the bug

Hi, I got a very strange bug or issue, i was searching for a solution and editing the gamemodes_server.txt file and also trying to set Ultimate-MapChooser.cfg but without any success....
At the end when the maptime expires and is time for voting for the next map I getting this error " [CS2-Ultimate-Mapchooser] Warning: mapgroup is null!
 [CS2-Ultimate-Mapchooser] No maps found!"

**Comment by kus** [comment]
You just be using a custom config.

Ultimate map chooser (my plugin) needs `css_mapgroup mg_surf` set. See the `surf.cfg` example https://github.com/kus/cs2-modded-server/blob/master/game/csgo/cfg/surf.cfg

This will pick up the maps from `gamemodes_server.txt` under map group `mg_surf` and choose a random one at the end.

It also allows admins to use !map in chat to change maps to a map from the current mod list.

**Comment by BorislavKolev1994** [comment]
Hi kus,
after changing the surf.cfg as you mentioned it i got the same problem :
Going to intermission...
16:33:32.048 [CS2-Ultimate-Mapchooser] Warning: mapgroup is null!
16:33:32.048 [CS2-Ultimate-Mapchooser] No maps found!

**Comment by BorislavKolev1994** [comment]
Hi kus, 
so the whole drama was that in the env.cfg  hast to be added css_mapgroup mg_surf and then we are good to go, but because there are 84 files in the /game/csgo/cfg directory I was confused , so after all after good clean of not used cfg's and checking the env.cfg i was able to figure out the issue. 
Thanks for the responses and the support.

**Comment by kus** [comment]
All good! Glad you sorted it out.

Thanks
