### ISSUE TITLE
[Feature]: Adding a Deathmatch-specific plugin

### ISSUE THREAD

**Issue by mavproductions** [kus/cs2-modded-server#47]
### Information

Hello again,
Please consider adding a deathmatch plugin for additional configurations such as multi-cfg and spawn editing.

Ex repo:
https://github.com/NockyCZ/CS2-Deathmatch

Thanks!

**Comment by kus** [comment]
This has been done in the latest update!

It has no default configuration at the moment so you'll need to play around with that yourself.
