### ISSUE TITLE
[Bug]: New CS2 Patch fixes

### ISSUE THREAD

**Issue by mavproductions** [kus/cs2-modded-server#49]
### Server is up to date

- [X] My server is up-to-date and I'm using the latest version of this mod from this github.

### I've followed the instructions

- [X] I've followed the instructions

### Game Server Login Token

- [X] I'm using a valid Game Server Login Token or running on LAN

### Operating System

Linux Ubuntu 20.04

### Which mod are you playing

Competitive, Deathmatch, Wingman, 1v1, Practice, Surf, Bhop, KZ

### Are you trying to host online or on LAN?

Online on a cloud host Google, AWS, Azure etc (please specify host)

### Metamod:Source Version

MM2.0 - build 1281

### Metamod:Source Plugins loaded

NA

### CounterStrikeSharp Version

Pending

### CounterStrikeSharp Plugins loaded

NA

### What is the bug

New CS2 Patch broke Metamod, and CSSharp. 

I know we can fix them manually, but it would be nice for such a major update if you included the fixes. 

Metamod build 1281 should work as of now, but CSS is still waiting for a patch.

Appreciate all you do.

**Comment by kus** [comment]
I was waiting for this. I checked last night and there was no updates, but looks like there is now.

Will update it now

**Comment by kus** [comment]
@mavproductions I've updated Metamod:Source and CounterStikeSharp to latest.

There isn't an update out yet for CounterStrikeSharp to fix it for the latest update but I have applied the [temporary fix](https://github.com/roflmuffin/CounterStrikeSharp/issues/309) which I've confirmed does work on Linux. There is no Windows signature yet.

When CounterStrikeSharp pushes an official update I will apply it.

**Comment by kus** [comment]
> > @mavproductions I've updated Metamod:Source and CounterStikeSharp to latest.
> > There isn't an update out yet for CounterStrikeSharp to fix it for the latest update but I have applied the [temporary fix](https://github.com/roflmuffin/CounterStrikeSharp/issues/309) which I've confirmed does work on Linux. There is no Windows signature yet.
> > When CounterStrikeSharp pushes an official update I will apply it.
> 
> I think tonight's update did more damage to metamod. I don't think metamod is working at the moment. Matchzy can work in CSS current state with ` "GameEventManager": { "offsets": { "windows": 93, "linux": 93 } }, "CEntityIOOutput_FireOutputInternal": { "signatures": { "library": "server", "windows": "\\x48\\x8B\\xC4\\x4C\\x89\\x48\\x20\\x55\\x57\\x41\\x54\\x41\\x56", "linux": "\\x55\\x48\\x89\\xE5\\x41\\x57\\x41\\x56\\x41\\x55\\x41\\x54\\x49\\x89\\xD4\\x53\\x48\\x89\\xF3\\x48\\x83\\xEC\\x58" } }` in gamedata.json but can't confirm if tonights patch that messed metamod also messed this recent temp fix for matchzy

This is the temporary fix I applied that I mentioned. I confirmed it does work in Linux.

**Comment by thanhhungtn1** [comment]
My server is still running fine with new cs2 update but countrerstrikesharp need to be up-to-date to run some plugins. Could we have an update to have the countrerstrikesharp running well with other plugins?

**Comment by kus** [comment]
@thanhhungtn1 FYI it's useful if you list that plugins that aren't working and any errors you are getting.

I updated every plugin yesterday less than 20 hours ago. The only thing that needs to be updateds again is CounterStrikeSharp which I just did.

**Comment by thanhhungtn1** [comment]
> @thanhhungtn1 FYI it's useful if you list that plugins that aren't working and any errors you are getting.
> 
> I updated every plugin yesterday less than 20 hours ago. The only thing that needs to be updateds again is CounterStrikeSharp which I just did.

Hi sorry for not replying soon. I have installed 3rd party plugins that required latest version of cssharp. Another problem I can found is changing the game mode via rcon to retakes cannot use rcon anymore.

**Comment by kus** [comment]
@thanhhungtn1 I fixed a bug today where CS2 Rcon wouldn't reload if it was unloaded when a plugin had the same functionality (like MatchZy). Does it work now?
