### ISSUE TITLE
[Bug]: Disable GOTV per default for 1v1 arena

### ISSUE THREAD

**Issue by pnallinger** [kus/cs2-modded-server#50]
### Server is up to date

- [X] My server is up-to-date and I'm using the latest version of this mod from this github.

### I've followed the instructions

- [X] I've followed the instructions

### Game Server Login Token

- [X] I'm using a valid Game Server Login Token or running on LAN

### Operating System

Linux Ubuntu 22.04

### Which mod are you playing

1v1

### Are you trying to host online or on LAN?

Online on a game hosting network (please specify host)

### Metamod:Source Version

 Build ID: 1282:3740821 Metamod:Source version 2.0.0-dev+1282 

### Metamod:Source Plugins loaded

 [01] CounterStrikeSharp (0.1.0) by Roflmuffin Listing 1 plugin:

### CounterStrikeSharp Version

Current API Version: 162

### CounterStrikeSharp Plugins loaded

 Supports multiple automatic 1v1 arenas with rank climbing. [#11:LOADED]: "CS2Multi1v1" (beta_1.0.0) by rockCityMath Remove the weapons from the map [#10:LOADED]: "Remove Map Weapons" (1.0.0) by Kus (https://steamcommunity.com/id/kus/) [#9:LOADED]: "Damage Info" (2.0.3) by K4ryuu Allows for server commands to be executed from the client using !rcon [#8:LOADED]: "CS2Rcon" (1.2.0) by LordFetznschaedl [#7:LOADED]: "SimpleAdmin" (0.1.2) Executes a command after server event or a delay. exec_after for help [#6:LOADED]: "CS2_ExecAfter" (1.0.0) by Kus (https://github.com/kus) https://github.com/yonilerner/cs2-retakes-allocator [#5:UNLOADED]: "Retakes Allocator Plugin" (1.2.13) by Yoni Lerner Community retakes for CS2. [#4:UNLOADED]: "Retakes Plugin" (1.3.24) by B3none Allow server owners to easily create unique configuration files on a per map basis. [#3:LOADED]: "[Custom] Map Configurator" (V. 1.0.2 [Beta]) by Manifest @Road To Glory Allows a CT to instantly defuse the bomb when nothing can prevent defusal. [#2:UNLOADED]: "Instadefuse Plugin" (1.4.2) by B3none The Ultimate Mapchooser for CS2! [#1:LOADED]: "CS2-Ultimate-Mapchooser" (1.0.0) by Kus (https://steamcommunity.com/id/kus/) List of all plugins currently loaded by CounterStrikeSharp: 11 plugins loaded.

### What is the bug

![Screenshot 2024-02-09 133301](https://github.com/kus/cs2-modded-server/assets/81702471/f777cb35-54e1-4a13-9615-8352b45a46bf)

The sourceTV is in queue for playing. 

### Steps to reproduce

Join server and switch to 1v1 and "!sq" to show the current queue

**Comment by kus** [comment]
@pnallinger I've pushed an update to disable GOTV for 1v1.

Please download the latest update (or if you use `install.sh` re-run it for the latest update) and let me know if that fixes it for you.
