### ISSUE TITLE
[Feature]: Change gamemode with something like RTV

### ISSUE THREAD

**Issue by 1xxn** [kus/cs2-modded-server#51]
### Information

hey, a gamemode voting feature would be cool, so the users can vote (like rock the vote) to choose the next gamemode (if no admin is online). 
Is that possible to implement that? Or could it be difficult due to rcon things?

best regards, 1xxn

**Comment by kus** [comment]
This is something I definately intend on including in my own RTV plugin which I'm working on.

My thought was if you run `!rtv` it has 3 options:

- Change map
- Change game mode
- Enable config (bunny hop is all I can think of at the moment)

Will keep you posted.

**Comment by kus** [comment]
@1xxn this has been done, read more [here](https://github.com/kus/cs2-modded-server?tab=readme-ov-file#gamemode).

Players can vote to change the current game mode by typing `!gamemode` in chat and also start a specific game mode vote by typing `!comp`, `!wingman`, `!dm`, `!gg`, `!1v1`, `!awp`, `!aim`, `!prefire`, `!executes`, `!retake`, `!prac`, `!bhop`, `!kz`, `!surf`, `!minigames`, `!course`, `!scoutzknivez`, `!hns`, `!soccer`
