### ISSUE TITLE
[Bug]: whole server crashes when selecting team while in surf gamemode

### ISSUE THREAD

**Issue by ALegitCookie** [kus/cs2-modded-server#53]
### Server is up to date

- [X] My server is up-to-date and I'm using the latest version of this mod from this github.

### I've followed the instructions

- [X] I've followed the instructions

### Game Server Login Token

- [X] I'm using a valid Game Server Login Token or running on LAN

### Operating System

Windows Server 2019

### Which mod are you playing

Surf

### Are you trying to host online or on LAN?

Online off a machine on my local network

### Metamod:Source Version

 2.0.0-dev+1282

### Metamod:Source Plugins loaded

CounterStrikeSharp (0.1.0)

### CounterStrikeSharp Version

 Current API Version: 166

### CounterStrikeSharp Plugins loaded

"CS2-Ultimate-Mapchooser" (1.0.0) , "CS2Rcon" (1.2.0) , "CS2_ExecAfter" (1.0.0) , "[Custom] Map Configurator" (V. 1.0.2 [Beta]) , "SimpleAdmin" (0.1.2)

### What is the bug

THIS ONLY HAPPENS AFTER I DO EXEC SURF
1. i start the server
2. wait for it to start, then use exec surf from the console
3. the server switches maps
4. i join
5. i am prompted to choose a team
6. i click a team (CT)
7. the whole server crashes

console output:
![IMG_7610](https://github.com/kus/cs2-modded-server/assets/39338269/363710fc-15d0-4307-a71f-1556a205bc83)

**Comment by kus** [comment]
@ALegitCookie thanks for bringing this to my attention. I have reproduced this error on my end also and can confirm it only affects Surf, other modes like GunGame work fine.

It appears there are some outdated signatures for Windows after the Arms Race CS2 update.

I have made a [ticket ](https://github.com/DEAFPS/SharpTimer/issues/39) on the Surf plugin authors repo and mentioned it in their discord (they are already aware of it).

I will keep you posted here if I see any fixes.

**Comment by ALegitCookie** [comment]
> I have made a [ticket ](https://github.com/DEAFPS/SharpTimer/issues/39) on the Surf plugin authors repo

thank you sorry if i posted this on the wrong repo

**Comment by 1xxn** [comment]
I had also this issue yesterday, it was an windows only issue. after switching back to ubuntu no error exists anymore

**Comment by kus** [comment]
@ALegitCookie no it's all good you can report here. This repo is meant to be so anyone can set up a pre-modded server really easy. So not on you to know what mods what. Report here, I can sus it out and confirm then report to the mod author if required.

Good news this has been fixed, I just confirmed by running it on my Windows machine.
