### ISSUE TITLE
[Feature]: How can I change the game mode in which the server starts?

### ISSUE THREAD

**Issue by Kl4rkx** [kus/cs2-modded-server#58]
### Information

I remember back in the day I changed a setting and now my server every time it starts it starts up it runs "exec wingman" but now I don't know where that is that I put in and I want to change it to "surf" game mode.

### **Thanks for taking the time to read this**

**Comment by Kl4rkx** [comment]
Ok, I solved it, I just had to modify the file

/game/csgo/cfg/cfg/mapconfigs/de_dust2.cfg

### **closed**

**Comment by Kl4rkx** [comment]
Ok, I solved it, I just had to modify the file

/game/csgo/cfg/cfg/mapconfigs/de_dust2.cfg

### **closed**

**Comment by ALegitCookie** [comment]
> ### Information
> 
> I remember back in the day I changed a setting and now my server every time it starts it starts up it runs "exec wingman" but now I don't know where that is that I put in and I want to change it to "surf" game mode.
> 
> 
> 
> ### **Thanks for taking the time to read this**

what exactly did you do to make it exec a game mode on start? i'm thinking about starting a 1v1 arena server but i'd like it to exec the game mode automatically for me

**Comment by Kl4rkx** [comment]
> > ### Information
> > I remember back in the day I changed a setting and now my server every time it starts it starts up it runs "exec wingman" but now I don't know where that is that I put in and I want to change it to "surf" game mode.
> > ### **Thanks for taking the time to read this**
> 
> what exactly did you do to make it exec a game mode on start? i'm thinking about starting a 1v1 arena server but i'd like it to exec the game mode automatically for me

Only put "exec 1v1" in the file "/game/csgo/cfg/cfg/mapconfigs/de_dust2.cfg" and save
