### ISSUE TITLE
[Bug]: Cannot retrieve your public IP address...

### ISSUE THREAD

**Issue by EinfachRobin** [kus/cs2-modded-server#63]
### Server is up to date

- [X] My server is up-to-date and I'm using the latest version of this mod from this github.

### I've followed the instructions

- [X] I've followed the instructions

### Game Server Login Token

- [X] I'm using a valid Game Server Login Token or running on LAN

### Operating System

Linux Debian 11

### Which mod are you playing

No mod

### Are you trying to host online or on LAN?

Online on a cloud host Google, AWS, Azure etc (please specify host)

### Metamod:Source Version

didn't came that far

### Metamod:Source Plugins loaded

didn't came that far

### CounterStrikeSharp Version

didn't came that far

### CounterStrikeSharp Plugins loaded

didn't came that far

### What is the bug

I always get `ERROR: Cannot retrieve your public IP address...` when trying to run the script. I'm hosting on a Hetzner Cloud Instance with a public IPv4 adress.

### Server log output

```shell
root@debian-4gb-fsn1-1:/# cd / && curl --silent --output "gcp.sh" "https://raw.githubusercontent.com/kus/cs2-modded-server/master/gcp.sh" && chmod +x gcp.sh && bash gcp.sh
Starting on Debian GNU/Linux: 11...
With   71 Gb free space...
Updating Operating System...
Hit:1 http://mirror.hetzner.com/debian/packages bullseye InRelease
Hit:2 http://mirror.hetzner.com/debian/packages bullseye-updates InRelease
Hit:3 http://mirror.hetzner.com/debian/security bullseye-security InRelease
Hit:4 http://security.debian.org/debian-security bullseye-security InRelease
Hit:5 http://deb.debian.org/debian bullseye InRelease
Hit:6 http://deb.debian.org/debian bullseye-updates InRelease
Reading package lists...
Adding i386 architecture...
Installing required packages for Debian GNU/Linux: 11...
ERROR: Cannot retrieve your public IP address...
```

### Steps to reproduce

1. Logging into the server via SSH.
2. Starting the script with the command as in the setup guide.

**Comment by EinfachRobin** [comment]
I disabled IPv6 to fix the issue in case anybody else runs into the same problem

**Comment by GoalTV** [comment]
Found simple fix edit install.sh line

PUBLIC_IP=$(dig  +short myip.opendns.com @resolver1.opendns.com)

Change to 

PUBLIC_IP=$(dig -4 +short myip.opendns.com @resolver1.opendns.com)
