### ISSUE TITLE
[Feature]: Add Capture the Flag mod

### ISSUE THREAD

**Issue by mannumilano** [kus/cs2-modded-server#76]
### Information

Its possible add CTF mod in counter stiker 2?

**Comment by kus** [comment]
As far as I can tell there is no Capture The Flag mod for CS2.

You can request it in the official [CounterStrikeSharp discord](https://docs.cssharp.dev/) (top right) in the "plugin-requests" channel.

If you find an open source one that someone is working on, please do share here.
