### ISSUE TITLE
[Bug]: ERROR: Cannot retrieve your public IP address...

### ISSUE THREAD

**Issue by tklostermannNSD** [kus/cs2-modded-server#88]
### Server is up to date

- [X] My server is up-to-date and I'm using the latest version of this mod from this github.

### I've followed the instructions

- [X] I've followed the instructions

### Game Server Login Token

- [X] I'm using a valid Game Server Login Token or running on LAN

### Operating System

Linux Ubuntu 22.04

### Which mod are you playing

No mod

### Are you trying to host online or on LAN?

Online off my machine

### Metamod:Source Version

unknown

### Metamod:Source Plugins loaded

unknown

### CounterStrikeSharp Version

unknown

### CounterStrikeSharp Plugins loaded

unknown

### What is the bug

I can't install the server with the "install.sh" as the command "dig +short myip.opendns.com @resolver1.opendns.com" inside the install sh doesn't output an IP address.
I definitely have a public IPv4 address, but dig doesnt output it. This breaks the whole setup as I can't skip this or overwrite the public IP with an environment variable.

My host is a Contabo VPS

### Server log output

```shell
root@vmd10384:/# cd / && curl --silent --output "install.sh" "https://raw.githubusercontent.com/kus/cs2-modded-server/master/install.sh" && chmod +x install.sh && bash install.sh
Starting on Ubuntu: 22.04...
With   78 Gb free space...
Updating Operating System...
OK:1 http://asi-fs-n.contabo.net/ubuntu jammy InRelease
OK:2 http://asi-fs-n.contabo.net/ubuntu jammy-updates InRelease
OK:3 http://asi-fs-n.contabo.net/ubuntu jammy-backports InRelease
OK:4 https://download.docker.com/linux/ubuntu jammy InRelease
OK:5 http://security.ubuntu.com/ubuntu jammy-security InRelease
Paketlisten werden gelesen…
Adding i386 architecture...
Installing required packages for Ubuntu: 22.04...
ERROR: Cannot retrieve your public IP address...
```

### Steps to reproduce

cd / && curl --silent --output "install.sh" "https://raw.githubusercontent.com/kus/cs2-modded-server/master/install.sh" && chmod +x install.sh && bash install.sh

**Comment by unrealgeorge** [comment]
Same error

**Comment by Mr-Robot-ops** [comment]
Do you get your IP address displayed when you run the command normally? Please do not post your IP!

dig +short myip.opendns.com @resolver1.opendns.com

**Comment by kus** [comment]
An update has been pushed to force IPv4. This should hopefully fix the issue for you.

Can you confirm if it has?

If not, can you run this command, does it return an IP (don't share it): `dig -4 +short myip.opendns.com @resolver1.opendns.com`

**Comment by tklostermannNSD** [comment]
Sorry for the late answer, it works. ty
