### ISSUE TITLE
[Bug]: Potential access issue or write protection.

### ISSUE THREAD

**Issue by motaegrasa** [kus/cs2-modded-server#93]
### Server is up to date

- [X] My server is up-to-date and I'm using the latest version of this mod from this github.

### I've followed the instructions

- [X] I've followed the instructions

### Game Server Login Token

- [X] I'm using a valid Game Server Login Token or running on LAN

### Operating System

Windows 11

### Which mod are you playing

No mod

### Are you trying to host online or on LAN?

LAN off my machine

### Metamod:Source Version

none

### Metamod:Source Plugins loaded

none

### CounterStrikeSharp Version

none

### CounterStrikeSharp Plugins loaded

none

### What is the bug

After downloading CS2 from the win.bat, it won't start the server telling me 
![image](https://github.com/kus/cs2-modded-server/assets/52753455/8a186120-713b-4c4a-a624-09d317967496)

I've tried giving myself every single type of ownership and acces and the list goes on, but none worked. Currently i have no idea and i ve never seen someone with the same problem

### Game console output

```shell
none
```

### Server log output

```shell
If you want to quit, close the CS2 window and type Y followed by Enter.
Using SteamCMD to check for updates.
Backup file server\game\csgo\gameinfo.gi already exists.
Checking if server\game\csgo\gameinfo.gi has already been patched...
'findstr' is not recognized as an internal or external command,
operable program or batch file.
server\game\csgo\gameinfo.gi needs to be patched...
'findstr' is not recognized as an internal or external command,
operable program or batch file.
Temporary file server\game\csgo\gameinfo.gi.tmp created successfully. Preparing to replace server\game\csgo\gameinfo.gi...
        1 file(s) moved.
Failed to replace original file. Error: 9009
Press any key to continue . . .
```

### Steps to reproduce

1.Use windows
2.First time launch win.bat
3.See for yourself.

**Comment by Mr-Robot-ops** [comment]
This may solve the problem:

```
Please google it, you can find a lot of answers. But do as below to fix it. 
Add the following value to Right Click My Compuer -> Advanced -> Environment Variables -> System Variables -> Select Path variable -> append the below value.

C:\WINDOWS\system32 

It should work with that change.
```

It can't hurt to log off briefly afterwards.

[https://stackoverflow.com/questions/10244181/findstr-is-not-recognized-as-an-internal-or-external-command](https://stackoverflow.com/questions/10244181/findstr-is-not-recognized-as-an-internal-or-external-command)
[https://answers.microsoft.com/en-us/windows/forum/all/findstr-is-not-recognized-as-an-internal-or/87f77967-538c-4a77-a9d8-917b6e577a84](https://answers.microsoft.com/en-us/windows/forum/all/findstr-is-not-recognized-as-an-internal-or/87f77967-538c-4a77-a9d8-917b6e577a84)

**Comment by kus** [comment]
@motaegrasa can you please confirm if what @Mr-Robot-ops said fixed the issue for you?

`findstr` is bundled with Windows. For some reason your system doesn't know how to find it. Updating your path to search `C:\WINDOWS\system32` should fix it.
