### ISSUE TITLE
[Bug]: Retake plugin is active all the time

### ISSUE THREAD

**Issue by RennieSs** [kus/cs2-modded-server#95]
### Server is up to date

- [X] My server is up-to-date and I'm using the latest version of this mod from this github.

### I've followed the instructions

- [X] I've followed the instructions

### Game Server Login Token

- [X] I'm using a valid Game Server Login Token or running on LAN

### Operating System

Windows 11

### Which mod are you playing

Other (please specify)

### Are you trying to host online or on LAN?

Online off a machine on my local network

### Metamod:Source Version

Source version 2.0.0-dev+1291

### Metamod:Source Plugins loaded

 [01] CounterStrikeSharp (v0 @ 9a221b4) by Roflmuffin   [02] Fake RCON (1.2.2) by Kriax

### CounterStrikeSharp Version

Version: v227 (1.0.227+9a221b4)

### CounterStrikeSharp Plugins loaded

  [#1:LOADED]: "Clutch Announce Plugin" (1.1.0) by B3none     Announce when someone wins a clutch scenario   [#2:LOADED]: "CS2-Ultimate-Mapchooser" (1.0.0) by Kus (https://steamcommunity.com/id/kus/)     The Ultimate Mapchooser for CS2!   [#3:LOADED]: "CS2Rcon" (1.2.0) by LordFetznschaedl     Allows for server commands to be executed from the client using !rcon   [#4:LOADED]: "CS2_ExecAfter" (1.0.0) by Kus (https://github.com/kus)     Executes a command after server event or a delay. exec_after for help   [#5:LOADED]: "Practice Plugin" (1.0.0.2) by CHR15 & Gr├╝kan   [#6:LOADING]: "GameModeManager" (1.0.1) by Striker-Nick     A simple plugin/module that dynamically updates any maplist.txt file based on the current mapgroup.   [#7:UNLOADED]: "Instadefuse Plugin" (1.4.3) by B3none     Allows a CT to instantly defuse the bomb when nothing can prevent defusal.   [#8:UNLOADED]: "Instaplant Plugin" (1.0.0) by B3none     Allows a terrorist to instantly plant the bomb.   [#9:LOADED]: "KPS Allocator" (0.2.1) by Nokkvi Reyr   [#10:LOADED]: "[Custom] Map Configurator" (V. 1.0.2 [Beta]) by Manifest @Road To Glory     Allow server owners to easily create unique configuration files on a per map basis.   [#11:LOADING]: "Resource Precacher" (1.0.3 (release)) by Nexd @ Eternar (https://eternar.dev)     Automatically precache resources.   [#12:LOADED]: "RockTheVote" (1.8.5) by abnerfs     https://github.com/abnerfs/cs2-rockthevote   [#13:LOADED]: "SimpleAdmin" (0.1.2)   [#14:LOADED]: "Damage Info" (2.3.2) by K4ryuu

### What is the bug

In all modes and maps, the retake plugin takes over. starts retake map vote when map is done etc. how do i fix this?

**Comment by kus** [comment]
Your server is modified from the repo.

Unfortunately I can’t help if you have added additional plugins.

To try narrow down the root cause; delete everything (or move it) and start from scratch with my repo and check that works correctly (it should) then slowly add back your other plugins one at a time.
